name: moviles
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  permission_handler: ^11.0.0
  geolocator: ^10.1.0
  flutter_cache_manager: ^3.3.1
  provider: ^6.0.5
  dio: ^5.3.3
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

