// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrlG3yMGAUhCaQSdTjU7EWPIg01d_mys',
    appId: '1:947310673139:web:bff526adb909156d5ccb86',
    messagingSenderId: '947310673139',
    projectId: 'appflutter-29a25',
    authDomain: 'appflutter-29a25.firebaseapp.com',
    storageBucket: 'appflutter-29a25.appspot.com',
    measurementId: 'G-VB2GHVT8KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8sVjXA5hpRf3UKkbklMPvaqde73ewCWU',
    appId: '1:947310673139:android:915df52a378537025ccb86',
    messagingSenderId: '947310673139',
    projectId: 'appflutter-29a25',
    storageBucket: 'appflutter-29a25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBhBW3VYfrGpGYYhhA7nIRV9cWCq-eGnM',
    appId: '1:947310673139:ios:398e655d51b4201d5ccb86',
    messagingSenderId: '947310673139',
    projectId: 'appflutter-29a25',
    storageBucket: 'appflutter-29a25.appspot.com',
    iosBundleId: 'com.example.moviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBhBW3VYfrGpGYYhhA7nIRV9cWCq-eGnM',
    appId: '1:947310673139:ios:6eaa8a4636046c165ccb86',
    messagingSenderId: '947310673139',
    projectId: 'appflutter-29a25',
    storageBucket: 'appflutter-29a25.appspot.com',
    iosBundleId: 'com.example.moviles.RunnerTests',
  );
}
